create table author (
        id bigint generated by default as identity (start with 1),
        first_name varchar(255),
        last_name varchar(255),
        middle_name varchar(255),
        primary key (id)
);

create table book (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        author_id bigint,
        genre_id bigint,
        publisher varchar(255),
        year varchar(255),
        city varchar(255),
        primary key (id)
);

create table genre (
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        primary key (id)
);

alter table book
       add constraint FKklnrv3weler2ftkweewlky958
       foreign key (author_id)
       references author

alter table book
       add constraint FKm1t3yvw5i7olwdf32cwuul7ta
       foreign key (genre_id)
       references genre